
language: python
python:
  - 3.6

install:
  - pip install -e . --use-mirrors
  
before_script:
  - python --version
  - git clone https://github.com/ExLeonem/tf-al
  - cd tf-al
  - pytest --cov
  - cd -
  
script:
  - py.test coveralls/tests.py --doctest-modules --pep8 coveralls -v --cov coveralls --cov-report term-missing
  
after_success:
  - coveralls
  