language: python
python: 
  - "3.6"

before_install:
  - pip install poetry

install:
    - poetry install
    - pip install codeclimate-test-reporter

script:
    - poetry run coverage run --source=./tf_al -m pytest tests/

after_success:
  - poetry run coveralls

before_deploy:
- poetry config pypi-token.pypi $PYPI_TOKEN
- poetry build

deploy:
  provider: script
  script: poetry publish
  skip_cleanup: true
