name: Documentation publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:

  build:
    name: Push sphinx pages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        
      - name: Build and push
        uses: totaldebug/action-sphinx@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sphinx_src: "docs/"
          target_branch: "gh-pages"
